image:
  repository: apache/superset

serviceAccountName: spark-bucket-read-sa

supersetNode:
  replicaCount: 1

bootstrapScript: |
  #!/bin/bash
  uv pip install .[postgres] duckdb-engine &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

configOverrides:
  secret: |
    SECRET_KEY = os.environ.get('SECRET_KEY')
  feature_flags: |
    FEATURE_FLAGS = {
        "ENABLE_TEMPLATE_PROCESSING": True,
    }

envFromSecrets:
  - superset-secret-key
  - superset-aws-credentials


init:
  adminUser:
    username: admin
    firstname: Admin
    lastname: User
    email: admin@encodedcc.org
    password: changeme

extraConfigs:
  import_datasources.yaml: |
    databases:
    - database_name: igvf-parsed-logs
      sqlalchemy_uri: "duckdb:///:memory:"
      extra: "{\"engine_params\": {\"connect_args\": {\"config\": {\"s3_region\": \"us-west-2\", \"autoinstall_known_extensions\": true, \"autoload_known_extensions\": true}}}}"
      allow_ctas: false
      allow_cvas: false
      allow_file_upload: false
      tables: []

postgresql:
  enabled: true
  auth:
    username: superset
    password: superset
    database: superset

redis:
  enabled: true
