supersetNode:
  replicaCount: 1

bootstrapScript: |
  #!/bin/bash
  uv pip install .[postgres] &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

configOverrides:
  secret: |
    SECRET_KEY = os.environ.get('SECRET_KEY')
  feature_flags: |
    FEATURE_FLAGS = {
        "ENABLE_TEMPLATE_PROCESSING": True,
    }

extraEnvFrom: |
  - secretRef:
      name: superset-secret-key

init:
  adminUser:
    username: admin
    firstname: Admin
    lastname: User
    email: admin@encodedcc.org
    password: changeme

postgresql:
  enabled: true
  auth:
    username: superset
    password: superset
    database: superset

redis:
  enabled: true
