apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-encode-blobs-dev-pv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - region us-west-2
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-encode-blobs-dev-driver-volume
    volumeAttributes:
      bucketName: encoded-blobs-dev