apiVersion: apps/v1
kind: Deployment
metadata:
  name: testsecretsapp
spec:
  selector:
    matchLabels:
      app: testsecretsapp
  template:
    metadata:
      labels:
        app: testsecretsapp
    spec:
      serviceAccountName: test-secrets-store-sa
      volumes:
        - name: secretsvolume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: hello-world-secrets
      containers:
        - name: testsecretsapp
          image: nginx:latest
          volumeMounts:
            - name: secretsvolume
              mountPath: /tmp
          env:  # Add the environment variable section here
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eks-test-secret  # The name of the Kubernetes Secret
                  key: secretPassword       # The key in the Kubernetes Secret
