apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hello-world-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "eks-test-secret"
          objectType: "secretsmanager"
