apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hello-world-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "eks-test-secret"
          objectType: "secretsmanager"
  secretObjects:                              # [OPTIONAL] Define the Kubernetes Secret to sync
    - secretName: eks-test-secret              # Name of the Kubernetes Secret
      type: Opaque                            # Type of the Kubernetes Secret
      data:
        - objectName: "eks-test-secret"       # Name of the mounted content to sync
          key: secretValue       
