apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arango-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-arangodb
    repoURL: https://arangodb.github.io/kube-arangodb
    targetRevision: 1.2.43
    helm:
      releaseName: kube-arangodb
      valuesObject:
        operator:
          features:
            storage: true
            backup: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
