apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-spark
  namespace: data-stack-dev
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: public.ecr.aws/cherry-lab/cherry-lab:spark-3.5.4-s3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: https://raw.githubusercontent.com/keenangraham/cdk-kubernetes/refs/heads/main/spark/test-spark.py
  sparkVersion: 3.5.3
  driver:
    coreRequest: "1000m"
    memory: "2048M"
    serviceAccount: spark-bucket-read-sa
    env:
      - name: IVY_CACHE_DIR
        value: /tmp/.ivy2
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-spark-access-key
            key: ACCESS_KEY
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-spark-secret-access-key
            key: SECRET_ACCESS_KEY
    volumeMounts:
      - name: ivy-cache
        mountPath: /tmp/.ivy2
      - name: aws-creds
        mountPath: /tmp/.aws-creds
  executor:
    instances: 1
    coreRequest: "100m"
    memory: "512M"
    serviceAccount: spark-bucket-read-sa
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-spark-access-key
            key: ACCESS_KEY
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-spark-secret-access-key
            key: SECRET_ACCESS_KEY
    volumeMounts:
      - name: aws-creds
        mountPath: /tmp/.aws-creds
  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    maxExecutors: 10
    minExecutors: 1
  volumes:
    - name: ivy-cache
      emptyDir: {}
    - name: aws-creds
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "spark-aws-secrets"
