apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-spark-secret
  namespace: data-stack-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-spark-secret
  template:
    metadata:
      labels:
        app: test-spark-secret
    spec:
      volumes:
        - name: aws-creds
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "spark-aws-secrets"
      containers:
      - command:
        - /bin/sh
        - -c
        - tail -f /dev/null
        env:
        - name: QUEUE_URL
          value: https://sqs.us-west-2.amazonaws.com/618537831167/KubernetesStack-TestEksQueueD2A233F2-XOjvBnJ7HP9U
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-spark-access-key
              key: ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-spark-secret-access-key
              key: SECRET_ACCESS_KEY
        image: python:3.12.1-bullseye
        imagePullPolicy: IfNotPresent
        name: python
        volumeMounts:
          - name: aws-creds
            mountPath: /tmp
      serviceAccount: spark-bucket-read-sa
      serviceAccountName: spark-bucket-read-sa
