apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: parse-igvf-logs
  namespace: data-stack-dev
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: public.ecr.aws/cherry-lab/cherry-lab:spark-4.1.2-s3.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: https://raw.githubusercontent.com/keenangraham/cdk-kubernetes/refs/heads/main/spark/parse-igvf-logs.py
  sparkVersion: 4.1.2
  timeToLiveSeconds: 600
  driver:
    labels:
      app.kubernetes.io/name: "parse-igvf-logs"
    annotations:
      karpenter.sh/do-not-disrupt: "true"
    coreRequest: "2000m"
    memory: "4096M"
    serviceAccount: spark-bucket-read-sa
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-spark-access-key
            key: ACCESS_KEY
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-spark-secret-access-key
            key: SECRET_ACCESS_KEY
      - name: IGVF_FILES_LOGS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-spark-igvf-files-logs-access-key
            key: ACCESS_KEY
      - name: IGVF_FILES_LOGS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-spark-igvf-files-logs-secret-access-key
            key: SECRET_ACCESS_KEY
      - name: DATE
        value: "{{ ds }}"
    volumeMounts:
      - name: aws-creds
        mountPath: /tmp/.aws-creds
      - name: igvf-files-logs-creds
        mountPath: /tmp/.igvf-files-logs-creds
  volumes:
    - name: aws-creds
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "spark-aws-secrets"
    - name: igvf-files-logs-creds
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "spark-igvf-files-logs-secrets"
  executor:
    annotations:
      karpenter.sh/do-not-disrupt: "true"
    cores: 2
    coreRequest: "1000m"
    memory: "2048M"
    serviceAccount: spark-bucket-read-sa
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-spark-access-key
            key: ACCESS_KEY
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-spark-secret-access-key
            key: SECRET_ACCESS_KEY
      - name: IGVF_FILES_LOGS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-spark-igvf-files-logs-access-key
            key: ACCESS_KEY
      - name: IGVF_FILES_LOGS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-spark-igvf-files-logs-secret-access-key
            key: SECRET_ACCESS_KEY
    volumeMounts:
      - name: aws-creds
        mountPath: /tmp/.aws-creds
      - name: igvf-files-logs-creds
        mountPath: /tmp/.igvf-files-logs-creds
  volumes:
    - name: aws-creds
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "spark-aws-secrets"
    - name: igvf-files-logs-creds
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "spark-igvf-files-logs-secrets"
  dynamicAllocation:
    enabled: true
    initialExecutors: 6
    maxExecutors: 10
    minExecutors: 1
  sparkConf:
    "spark.hadoop.fs.s3a.connection.maximum": "100"
    "spark.hadoop.fs.s3a.fast.upload": "true"
    "spark.hadoop.fs.s3a.multipart.size": "67108864"
