apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-spark
  namespace: data-stack-dev
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: public.ecr.aws/cherry-lab/cherry-lab:spark-3.5.4-s3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: https://raw.githubusercontent.com/keenangraham/cdk-kubernetes/refs/heads/main/spark/test-spark.py
  sparkVersion: 3.5.3
  driver:
    labels: 
      app.kubernetes.io/name: "test-spark-app"
    coreRequest: "1000m"
    memory: "2048M"
    serviceAccount: spark-bucket-read-sa
  executor:
    coreRequest: "100m"
    memory: "512M"
    serviceAccount: spark-bucket-read-sa
  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    maxExecutors: 10
    minExecutors: 1
  sparkConf:
      "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
      "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"