apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-spark
  namespace: data-stack-dev
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark:3.5.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: https://raw.githubusercontent.com/keenangraham/cdk-kubernetes/refs/heads/main/spark/test-spark.py
  sparkVersion: 3.5.3
  driver:
    labels: 
      app.kubernetes.io/name: "test-spark-app"
    coreRequest: "1000m"
    memory: "2048M"
    serviceAccount: spark-bucket-read-sa
  executor:
    coreRequest: "100m"
    memory: "512M"
    serviceAccount: spark-bucket-read-sa
  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    maxExecutors: 5
    minExecutors: 1
  sparkConf:
      "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
      "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
      "spark.jars.packages": "org.apache.hadoop:hadoop-aws:3.4.1, software.amazon.awssdk:aws-sdk-java:2.31.36"
      "spark.hadoop.fs.s3a.sdk.version": "2"