apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
  namespace: data-stack-dev
spec:
  replicas: 1
  shards: 1
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 200Gi
  containerTemplate:
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: clickhouse-loader-aws-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: clickhouse-loader-aws-credentials
            key: AWS_SECRET_ACCESS_KEY
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
  keeperClusterRef:
    name: clickhouse-keeper
  settings:
    defaultUserPassword:
      secret:
        name: clickhouse-password
        key: password
