apiVersion: v1
kind: Secret
metadata:
  name: cdk-kubernetes-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/keenangraham/cdk-kubernetes.git
  type: git
